site_name: Sciurus Doku
dev_addr: '0.0.0.0:8080'
theme:
    name: null
    custom_dir: 'themes/material/'
    language: de
    palette:
      primary: indigo
      accent: indigo
    font:
      text: Roboto
      code: Roboto Mono
    logo:
      icon: "\uE80C"
    feature:
      tabs: true
      
markdown_extensions:
    - admonition
    - fenced_code
    - codehilite

nav:
    - Home: 'index.md'
    - Section:
        - Test: 'chapter/test.md'
