site_name: Mkdocs Skeleton
theme:
    name: 'material'
    language: en
    palette:
        primary: black
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.expand
        - navigation.indexes
    plugins:
        - search:
            lang: en

markdown_extensions:
    - 'admonition'
    - 'pymdownx.highlight'
    - 'pymdownx.keys'
    - 'pymdownx.superfences'
    - pymdownx.tabbed:
          alternate_style: true
    - 'attr_list'
    - 'md_in_html'

nav:
    - Common:
        - 'index.md'
    - Demo:
        - 'demo/index.md'
